language: java
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - "/^v[0-9].*$/"
env:
  global:
  - secure: YLx0974ASCsAwss2Ft+1SK2DtK7jIRJAkOid4qsb++oqVPaMLhYM/9wUsx0k0dU5EZB4tmMG8ATA2UESvo6VG8iyYYsyrURuYwW7XRGeyt154zw4LwiEZMOQblxpNUpvEMRW1P3TkqqBa8B31oD5McXwdh+XWzky9zj0u426tWqS4tQbc053PORVlYn4zeoK4yEB6qcN/FaJksXosgqae9RSRa2z0Fd3jDjqNqM4WaVxvjpwbbcQzKb+SWB4/nMOQ/mYvz8rewFE/bxxxsvpca/A10z5XfhUUdBwnADDAX+LLz/77oX6CcaPLjsSpn48VJKuhqBxj7Py7aSvgZvI3qArlbAkr+cfZXMuh2c+ukq/2nt0i82wb2hVJW3A6qsH3LiEA/0FrTX7jhUH9Bar8a+qNC79C9h8Qb9qwxUD8ZjOqRvcktTaGoCyQlsnBkfPg4IbEqcTSUe9uzYt2ae+MhY2fxBmguhFSPHC0/hF6gFMbGdjyCpX98rCoQMJ4puo0FICxvvxPRaIQEsNdjJrUlB1mvihtRs7S8MdRxhm0CetQYvCkYgVJwHfTkGhuxq45SSlDDt1RS+Vsi7omJMQtGLYP1lSzySnHrKNJsIr3TAgaHS+ONpaRO9T8vOoW1NGm6HuDWamHHfik+OfYShw3jn9RRg5RgN6YeKox6QOxtw=
git:
  submodules: false
notifications:
  email: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- mvn versions:set -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} -DnewVersion=${TRAVIS_TAG:1}
install:
- mvn -nsu -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} install
deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file_glob: true
  file:
  - Structure-API-Plugin/target/StructureAPI*.jar
  - Structure-API-Plugin/target/classes/gettext-report.txt
  - changelog.md
  - Structure-API/target/Structure-API*.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
  prerelease: true
cache:
  directories:
  - "$HOME/.m2"
